
stages:
  - pre_setup
  - build
  - test
  - docker_build_push

variables:
  APP_NAME: ""
  APP_VERSION: ""
  DOCKER_REGISTRY: "docker.io"


before_script: |
  echo "CI_ENVIRONMENT_FILE=$CI_ENVIRONMENT_FILE"
  echo "before_script"


set_env_variables:
  stage: pre_setup
  image: node:20
  script:
    - export APP_NAME=$(node -p "require('./package.json').name")
    - export APP_VERSION=$(node -p "require('./package.json').version")
    - echo "APP_NAME=$APP_NAME" >> $CI_ENVIRONMENT_FILE
    - echo "APP_VERSION=$APP_VERSION" >> $CI_ENVIRONMENT_FILE
  rules:
    - when: always


build:
  needs: [set_env_variables]
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/angular-weather-app


test:
  needs: [set_env_variables]
  stage: test
  script:
    - npm run test
  artifacts:
    reports:
      junit: unit-test-results.xml
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_TAG'  # Check if it's master or a tag
      allow_failure: true  # Allow this job to fail without failing the pipeline



docker_image_tag:
  needs: [build, set_env_variables]
  stage: docker_image
  image: docker:latest
  services:
    - docker:dind
  script:
    - source $CI_ENVIRONMENT_FILE  # Load environment variables
   # get the tag name or branch commit sha
    - if [ -z "$CI_COMMIT_TAG" ]; then
        export IMAGE_TAG=$CI_COMMIT_SHA
      else
        export IMAGE_TAG=$CI_COMMIT_TAG
      fi
    - echo "IMAGE_TAG=$IMAGE_TAG"


docker_build:
  needs: [build, docker_image_tag]
  stage: docker_build_push
  image: docker:latest
  services:
    - docker:dind
  script:
    - source $CI_ENVIRONMENT_FILE  # Load environment variables
    - echo "APP_NAME:APP_VERSION=$APP_NAME:$APP_VERSION"
    - docker build . -t $APP_NAME:$APP_VERSION


docker_push:
  needs: [docker_build]
  stage: docker_build_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
  script:
    - source $CI_ENVIRONMENT_FILE  # Load environment variables
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin $DOCKER_REGISTRY
    - docker tag $APP_NAME:$APP_VERSION $DOCKER_REGISTRY/$APP_NAME:$APP_VERSION
    - docker push $APP_NAME:$APP_VERSION

