---
name: Master Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REPO_NAME: ""
  VERSION: ""
  IMAGE_TAG: ""

jobs:


  setup-build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          VERSION=${GITHUB_REF#refs/tags/}

          echo "REPO_NAME:VERSION=${REPO_NAME}:${VERSION}"

          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: set env
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "REPO_NAME:VERSION=${REPO_NAME}:${VERSION}"
        
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build




  docker_build_push:

    runs-on: ubuntu-latest
    needs: [setup-build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Set image tag
        id: vars
        run: |
          # Check if the ref is a tag or a branch
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          else
            IMAGE_TAG="$(echo ${GITHUB_SHA} | cut -c1-7)"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}"  # Echo for logging
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV


      - name: Debug Environment Variables for docker push
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          VERSION: ${{ env.VERSION }}
        run: |
          echo "REPO_NAME=${{ env.REPO_NAME }}"
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"
          echo "VERSION=${{ env.VERSION }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}


